### ISSUE TITLE
edit branch name 

### ISSUE THREAD

**Issue by rowanibrahem** [MOHAMEDESAMX/chat_app#2]
it's called branch " dev " not div

in folder core the file called "constants " not a you write please solve it 

في فايل الالوان انت عامل colors.white احنا مبنحطش الالوان الاساسية في الفايل دا

**Comment by MOHAMEDESAMX** [comment]
تمام هعدلها بس انا افتكرت لازم نخط كل الالوان هنا علشان نعمل مثلا دارك ثيم وكده الله اعلم بس شكرا عالمعلومه هعدلهم حالا
