### ISSUE TITLE
edit ui 

### ISSUE THREAD

**Issue by rowanibrahem** [MOHAMEDESAMX/chat_app#3]
احنا بنحط الscaffold في فايل الview مش في فايل الwidgets لان للview  دا هو اللي بيعبر عن الاسكرينة الاساسية و الwidgets اللي جواها 
![image](https://github.com/user-attachments/assets/62f20cc2-abb3-4c84-a34c-11e2448a3cbd)

**Comment by MOHAMEDESAMX** [comment]
تمام عملت كده
